FROM node:18-alpine as build
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm install --no-audit --no-fund
COPY frontend .
RUN npm run build

FROM node:18-alpine as run
WORKDIR /app
COPY --from=build /app/build ./build
RUN npm install -g serve@14.2.0 && mkdir -p .empty && mv ./build/* .empty/ && mv .empty ./build
EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]
